name: generate

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Clean old OPML
        run: rm *.xml
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dropbox
      - name: Download
        run: |
          python download.py ${{ secrets.DROPBOX_APP_KEY }} ${{ secrets.DROPBOX_APP_SECRET }} ${{ secrets.DROPBOX_API_KEY }}
      - name: Generate README
        run: python deploy.py
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
