name: CI

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean old OPML
        run: rm *.xml
      - name: Download new OPML
        run: |          
          curl -s \
          -H "Cookie: ssid=${{ secrets.SSID }}; al=${{ secrets.AL }};" \
          https://www.inoreader.com/reader/subscriptions/export?download=1 \
          -o "subscriptions.xml"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Generate README
        run: python deploy.py
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
